name: jemalloc

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:

    - name: Clone Main Repository
      uses: actions/checkout@v2
      with:
        submodules: true
        ssh-key: ${{secrets.SSH_KEY_FOR_ACTIONS}}
        persist-credentials: false

    - name: Create Build Environment
      shell: bash
      run: |
        sudo apt-get install -y build-essential cmake
        cmake -E make_directory ${{github.workspace}}/build

    - name: Download jemalloc
      shell: bash
      working-directory: /usr/local/src
      run: |
        sudo wget https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2
        sudo tar xvf jemalloc-5.2.1.tar.bz2

    - name: Install jemalloc
      continue-on-error: true
      shell: bash
      working-directory: /usr/local/src/jemalloc-5.2.1
      run: |
        sudo ./configure --prefix=/usr/local --with-version=VERSION --with-jemalloc-prefix=je_ --with-install-suffix=_without_override --disable-cxx
        sudo make -j
        sudo make install

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMEMORY_MANAGER_USE_JEMALLOC=ON -DMEMORY_MANAGER_BUILD_TESTS=ON -DMEMORY_MANAGER_TEST_THREAD_NUM=2

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE
